<?php

/**
 * @file
 * Allows the creation of a Twitter field.
 */

/**
 * Implements hook_theme().
 */
function kees_twitter_field_theme($existing, $type, $theme, $path) {
  return [
    'kees_twitter_field' => [
      'variables' => [],
    ],
    'kees_twitter_field_formatter' => [
      'template' => 'field--kees-twitter-field',
      'variables' => [
        "content" => NULL,
      ],
    ],
  ];
}
