<?php

/**
 * @file
 * Allows the creation of a Twitter field.
 */

/**
 * Implements hook_theme().
 */
function twitter_field_theme($existing, $type, $theme, $path) {
  return [
    'twitter_field' => [
      'variables' => [],
    ],
    'twitter_field_formatter' => [
      'template' => 'field--twitter-field',
      'variables' => [
        "tweets" => NULL,
        "type" => NULL,
        "filter" => NULL,
      ],
    ],
  ];
}
